# Generated by Django 5.1.4 on 2025-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_menuitem_is_item_of_the_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_item_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
