# Generated by Django 5.1.4 on 2025-01-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_menuitem_is_item_of_the_day_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_item_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Savory', 'Savory'), ('Sweet', 'Sweet'), ('Drinks', 'Drinks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
